### ISSUE TITLE
Text has "+"

### ISSUE THREAD

**Issue by johnvic** [ChristianGiupponi/Laravel-4-Nexmo#1]
Hello,

Thank you for this package. But I have an issue, I successfully received the message and the message appears to be like this.
This+is+a+test+message

How can I resolve this?

thanks

**Comment by ChristianGiupponi** [comment]
Hi @johnvic ,
this is a quick fix that has not been released yet, go in:

```
vendor/christian-giupponi/nexmo/src/ChristianGiupponi/Nexmo/Nexmo.php
```

and in the `sendSMS` function in the `$required` array do this chenge:

```
'text' => htmlentities( $text )
```

now it should work

**Comment by johnvic** [comment]
Hello Christian,

Thanks for the quick response. Yes, I have gone into that file and see the urlencode($text) line. I have removed the urlencode as of the moment. But I will add htmlentities as your suggestion.
But this will be reverted every time I will do composer update. Am i right?

**Comment by ChristianGiupponi** [comment]
I will update later today so I think that composer update should be "safe"

**Comment by ChristianGiupponi** [comment]
Just pushed the fix https://github.com/ChristianGiupponi/Laravel-4-Nexmo/commit/59e340f6550878db16f07213c75c9b731f8ce624
